### ISSUE TITLE
support and feedback

### ISSUE THREAD

**Issue by shanil-sasikumar** [shanil-sasikumar/Feedback#26]
### Feedback Details
```yaml
name: Shanil Sasikumar
        email: shanil.sasikumar@citrusinformatics.com
        subject: support and feedback
        message: |- This is text description
        submissionDate: 2024-11-28T06:40:56.590Z
```
